sudo: false
language: c++

notifications:
  email:
    on_success: change
    on_failure: always
git:
  depth: 5

env:
  global:
    - CMAKE_OPTIONS_GLOBAL="-DCMAKE_EXPORT_COMPILE_COMMANDS=ON"

compiler:
  - clang
  - gcc
os: linux

script:
  # initial run with options
  - mkdir -p debug_build
  - cd debug_build
  - cmake ${CMAKE_OPTIONS_GLOBAL} .. -DCMAKE_BUILD_TYPE=Debug
  - make -j2
  - ctest --output-on-failure
  - cd ..
  - mkdir -p release_build
  - cd release_build
  - cmake ${CMAKE_OPTIONS_GLOBAL} .. -DCMAKE_BUILD_TYPE=Release
  - make -j2
  - ctest --output-on_failure

after_script:
  - cat compile_commands.json
